apiVersion: apps/v1
kind: Deployment
metadata:
  name: halyard-deployment
  labels:
    app: hal
  name: hal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal
  template:
    metadata:
      labels:
        app: hal
    spec:
      serviceAccountName: spinnaker-service-account
      containers:
      - name: halyard
        image: gcr.io/spinnaker-marketplace/halyard:stable
        lifecycle:
            postStart:
              exec:
                command: #configure hal pod with k8 cluster
                  - "sh"
                  - "-c"
                  - >
                    cd &&
                    kubectl config set-cluster default --server=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt &&
                    kubectl config set-context default --cluster=default &&
                    token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) &&
                    kubectl config set-credentials user --token=$token &&
                    kubectl config set-context default --user=user &&
                    kubectl config use-context default