#!/bin/bash
cat <<-HEREDOC > ${CONFIG_PATH}
#
# A squid configuration generated by ${0} at container startup.
# See https://git.soma.salesforce.com/spinnaker/front50/blob/master/front50-web/config/front50.yml .
#
server:
  port: ${PORT}
spinnaker:
  redis:
    enabled: ${REDIS_ENABLED}
	HEREDOC

/usr/lib/spinnaker-front50/bin/front50