- hosts: all
  become: true
  tasks:
    - name: Install basic packages
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - ca-certificates
        - curl
        - net-tools

    - name: install Docker
      yum:
        name: docker
        state: present
        update_cache: true

    - name: start Docker
      service:
        name: docker
        state: started

    - name: disable SELinux
      command: setenforce 0

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: enable firewalld service
      service:
        name: firewalld
        enabled: yes
        daemon_reload: yes
        state: started
    
    - name: enable ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250/tcp
        - 10252/tcp
        - 10255/tcp
    - name: reload firewalld service
      service:
        name: firewalld
        enabled: yes
        daemon_reload: yes
        state: restarted

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: Install kubelet, kubeadm
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - kubelet
        - kubeadm

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        daemon_reload: yes
        state: restarted

- hosts: k8s-master
  become: yes
  tasks:
    - name: install kubectl
      yum:
        name: kubectl
        state: present
        allow_downgrade: yes