# Ansible playbook to setup all nodes in cluster.
- hosts: all
  become: true
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Run Cenos setup
      include: "setup-centos-playbook.yml"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Run Ubuntu setup
      include: "setup-ubuntu-playbook.yml"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: enable firewalld service
      service:
        name: firewalld
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        daemon_reload: yes
        state: restarted
# only for k8 master install kubectl
- hosts: k8s-master
  become: yes
  tasks:
    - name: install kubectl (Cent OS)
      yum:
        name: kubectl
        state: present
        allow_downgrade: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: install kubectl (ubuntu)
      apt:
        name: kubectl
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'