---
    - name: "Playiing ansible spinnaker install playbook"
      hosts: localhost
      connection: local
      tasks:
        - name: "Create Spinnkaer Service accounts"
          shell: "kubectl apply -f ./manifests/spin_acct.yml"
        - name: "Create Spinnkaer namespace"
          shell: "kubectl apply -f ./manifests/spin_namespace.yml"
        - name: "Create Spinnkaer services"
          shell: "kubectl apply -f ./manifests/spin_svcs.yml"

        - name: "Create halyard deployment in default namespace"
          shell: "kubectl apply -f ./manifests/hal_deploy.yml"

        - name: "Configure halyard with k8s cluster"
          shell: "kubectl apply -f ./manifests/hal_deploy.yml"
     