servers = [
    {
        :name => "k8s-master",
        :type => "master",
        :box => "bento/ubuntu-18.04",
        #:box  => "centos/7",
        :eth1 => "192.168.205.10",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-01",
        :type => "node",
        :box => "bento/ubuntu-18.04",
        #:box  => "centos/7",
        :eth1 => "192.168.205.11",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-02",
        :type => "node",
        :box => "bento/ubuntu-18.04",
        #:box  => "centos/7",
        :eth1 => "192.168.205.12",
        :mem => "4048",
        :cpu => "4"
    },
    {
        :name => "node-03",
        :type => "node",
        :box => "bento/ubuntu-18.04",
        #:box  => "centos/7",
        :eth1 => "192.168.205.13",
        :mem => "4048",
        :cpu => "4"
    }
]


Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|
                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--groups", "/Ballerina Development"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
                ## for master node attach additional disk for k8 volumne storage
                if opts[:type] == "master"
                    disk = './k8-storage.vdi'
                    unless File.exist?(disk)
                        v.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 10 * 1024]
                    end
                    v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
                end
            end
            config.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/setup-playbook.yml"
                ansible.extra_vars = {
                    node_ip: opts[:eth1],
                }
            end

            if opts[:type] == "master"
                config.vm.provision "ansible" do |ansible|
                    ansible.playbook = "kubernetes-setup/master-playbook.yml"
                    ansible.extra_vars = {
                        node_ip: opts[:eth1],
                    }
                end
            else
                config.vm.provision "ansible" do |ansible|
                    ansible.playbook = "kubernetes-setup/node-playbook.yml"
                    ansible.extra_vars = {
                        node_ip: opts[:eth1],
                    }
                end
            end
        end
    end
end